### ISSUE TITLE
Serializable interface

### ISSUE THREAD

**Issue by basz** [igbinary/igbinary#129]
Classes which implement `Serializable` should have `serialize` method called. It seems this library does not do that... Is that correct or am I making an assumption that is incorrect?

**Comment by TysonAndre** [comment]
https://github.com/igbinary/igbinary/blob/master/tests/igbinary_021.phpt

Yes, it calls serialize/unserialize. You can see it being called if you add an echo statement inside serialize/unserialize

**Comment by basz** [comment]
Okay that you

Becuase i am unable to serialize object with this library 

https://libraries.io/packagist/marc-mabe%2Fphp-enum It throws an exception on __sleep

**Comment by basz** [comment]
To clarify my objects all implement the provided EnumSerializableTrait

Here the exception https://github.com/marc-mabe/php-enum/blob/master/src/Enum.php#L84

Finally with 'serialize' everything works ok

Php712
Thought about what could be wrong?

**Comment by TysonAndre** [comment]
Can't tell you without a link to the project which is throwing, or (better) a self-contained file which throws for igbinary_serialize but not on serialize.

Which igbinary version are you using?

**Comment by basz** [comment]
Yeah it is actually the __wakeup that does not work


```
#!/usr/bin/env php
<?php

declare(strict_types=1);

(function () {
    ini_set('display_errors', 'on');
    error_reporting(E_ALL);

    $autoloadFiles = [
        __DIR__ . '/../../../vendor/autoload.php',
        __DIR__ . '/../../vendor/autoload.php',
        __DIR__ . '/../vendor/autoload.php',
        __DIR__ . '/vendor/autoload.php',
    ];

    chdir(__DIR__ . '/..');

    foreach ($autoloadFiles as $autoloadFile) {
        if (file_exists($autoloadFile)) {
            require_once $autoloadFile;
        }
    }

    class SomeEnum extends \MabeEnum\Enum implements Serializable
    {
        use \MabeEnum\EnumSerializableTrait;

        public const BLAH = 1;
    }

    $serialized = igbinary_serialize(SomeEnum::BLAH());
    $enum = igbinary_unserialize($serialized);
})();
```
```
php ./bin/test-igbinary.php 
PHP Fatal error:  Uncaught LogicException: Enums are not serializable in /home-projects/api-plhw-development/deploy/releases/20170210133916UTC/vendor/marc-mabe/php-enum/src/Enum.php:93
Stack trace:
#0 [internal function]: MabeEnum\Enum->__wakeup()
#1 /home-projects/api-plhw-development/deploy/releases/20170210133916UTC/bin/test-igbinary.php(47): igbinary_unserialize('\x00\x00\x00\x02\x17\x08SomeEnum\x1D...')
#2 /home-projects/api-plhw-development/deploy/releases/20170210133916UTC/bin/test-igbinary.php(50): {closure}()
#3 {main}
  thrown in /home-projects/api-plhw-development/deploy/releases/20170210133916UTC/vendor/marc-mabe/php-enum/src/Enum.php on line 93

Fatal error: Uncaught LogicException: Enums are not serializable in /home-projects/api-plhw-development/deploy/releases/20170210133916UTC/vendor/marc-mabe/php-enum/src/Enum.php:93
Stack trace:
#0 [internal function]: MabeEnum\Enum->__wakeup()
#1 /home-projects/api-plhw-development/deploy/releases/20170210133916UTC/bin/test-igbinary.php(47): igbinary_unserialize('\x00\x00\x00\x02\x17\x08SomeEnum\x1D...')
#2 /home-projects/api-plhw-development/deploy/releases/20170210133916UTC/bin/test-igbinary.php(50): {closure}()
#3 {main}
  thrown in /home-projects/api-plhw-development/deploy/releases/20170210133916UTC/vendor/marc-mabe/php-enum/src/Enum.php on line 93

```

```
api-plhw-development@s02:~/deploy/current$ php -i | grep igbinary
/etc/php/7.1/cli/conf.d/20-igbinary.ini,
igbinary
igbinary support => enabled
igbinary version => 2.0.1
igbinary APCU serializer ABI => 0
igbinary session support => yes
igbinary.compact_strings => On => On
igbinary support => yes
Available serializers => php, igbinary
Registered serializer handlers => php_serialize php php_binary igbinary msgpack wddx 
```

```
api-plhw-development@s02:~/deploy/current$ php -v
PHP 7.1.2-4+deb.sury.org~xenial+1 (cli) (built: Mar  2 2017 10:39:59) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3-3+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
```
