### ISSUE TITLE
Segmentation fault during `pecl upgrade` due to pecl overwriting shared library while it's in use

### ISSUE THREAD

**Issue by acsfer** [igbinary/igbinary#341]
Please let me know how to provide further information:

```
# pecl upgrade
downloading imagick-3.5.1.tgz ...
Starting to download imagick-3.5.1.tgz (301,411 bytes)
.............................................................done: 301,411 bytes
downloading igbinary-3.2.5.tgz ...
Starting to download igbinary-3.2.5.tgz (95,784 bytes)
...done: 95,784 bytes
33 source files, building
running: phpize
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
building in /tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5
running: /tmp/pear/temp/igbinary/configure --with-php-config=/opt/sp/php7.4/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /opt/sp/php7.4
checking for PHP includes... -I/opt/sp/php7.4/include/php -I/opt/sp/php7.4/include/php/main -I/opt/sp/php7.4/include/php/TSRM -I/opt/sp/php7.4/include/php/Zend -I/opt/sp/php7.4/include/php/ext -I/opt/sp/php7.4/include/php/ext/date/lib
checking for PHP extension directory... /opt/sp/php7.4/lib/php/extensions/no-debug-non-zts-20190902
checking for PHP installed headers prefix... /opt/sp/php7.4/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... gawk
checking whether to enable igbinary support... yes, shared
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking stdbool.h usability... yes
checking stdbool.h presence... yes
checking for stdbool.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking PHP version... PHP 7
checking for APCu includes... APCu in /opt/sp/php7.4/include/php
checking size of long... 8
checking compiler type... gcc
checking for a sed that does not truncate output... /usr/bin/sed
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/bash /tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/libtool --mode=compile cc -g -O2 -O2 -Wall -Wpointer-arith -Wcast-align -Wwrite-strings -Wswitch -finline-limit=10000 --param large-function-growth=10000 --param inline-unit-growth=10000 -I. -I/tmp/pear/temp/igbinary -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/include -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/main -I/tmp/pear/temp/igbinary -I/opt/sp/php7.4/include/php -I/opt/sp/php7.4/include/php/main -I/opt/sp/php7.4/include/php/TSRM -I/opt/sp/php7.4/include/php/Zend -I/opt/sp/php7.4/include/php/ext -I/opt/sp/php7.4/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/igbinary/src/php7/igbinary.c -o src/php7/igbinary.lo
mkdir src/php7/.libs
 cc -g -O2 -O2 -Wall -Wpointer-arith -Wcast-align -Wwrite-strings -Wswitch -finline-limit=10000 --param large-function-growth=10000 --param inline-unit-growth=10000 -I. -I/tmp/pear/temp/igbinary -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/include -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/main -I/tmp/pear/temp/igbinary -I/opt/sp/php7.4/include/php -I/opt/sp/php7.4/include/php/main -I/opt/sp/php7.4/include/php/TSRM -I/opt/sp/php7.4/include/php/Zend -I/opt/sp/php7.4/include/php/ext -I/opt/sp/php7.4/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/igbinary/src/php7/igbinary.c  -fPIC -DPIC -o src/php7/.libs/igbinary.o
/bin/bash /tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/libtool --mode=compile cc -g -O2 -O2 -Wall -Wpointer-arith -Wcast-align -Wwrite-strings -Wswitch -finline-limit=10000 --param large-function-growth=10000 --param inline-unit-growth=10000 -I. -I/tmp/pear/temp/igbinary -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/include -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/main -I/tmp/pear/temp/igbinary -I/opt/sp/php7.4/include/php -I/opt/sp/php7.4/include/php/main -I/opt/sp/php7.4/include/php/TSRM -I/opt/sp/php7.4/include/php/Zend -I/opt/sp/php7.4/include/php/ext -I/opt/sp/php7.4/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/igbinary/src/php7/hash_si.c -o src/php7/hash_si.lo
 cc -g -O2 -O2 -Wall -Wpointer-arith -Wcast-align -Wwrite-strings -Wswitch -finline-limit=10000 --param large-function-growth=10000 --param inline-unit-growth=10000 -I. -I/tmp/pear/temp/igbinary -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/include -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/main -I/tmp/pear/temp/igbinary -I/opt/sp/php7.4/include/php -I/opt/sp/php7.4/include/php/main -I/opt/sp/php7.4/include/php/TSRM -I/opt/sp/php7.4/include/php/Zend -I/opt/sp/php7.4/include/php/ext -I/opt/sp/php7.4/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/igbinary/src/php7/hash_si.c  -fPIC -DPIC -o src/php7/.libs/hash_si.o
/bin/bash /tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/libtool --mode=compile cc -g -O2 -O2 -Wall -Wpointer-arith -Wcast-align -Wwrite-strings -Wswitch -finline-limit=10000 --param large-function-growth=10000 --param inline-unit-growth=10000 -I. -I/tmp/pear/temp/igbinary -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/include -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/main -I/tmp/pear/temp/igbinary -I/opt/sp/php7.4/include/php -I/opt/sp/php7.4/include/php/main -I/opt/sp/php7.4/include/php/TSRM -I/opt/sp/php7.4/include/php/Zend -I/opt/sp/php7.4/include/php/ext -I/opt/sp/php7.4/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/igbinary/src/php7/hash_si_ptr.c -o src/php7/hash_si_ptr.lo
 cc -g -O2 -O2 -Wall -Wpointer-arith -Wcast-align -Wwrite-strings -Wswitch -finline-limit=10000 --param large-function-growth=10000 --param inline-unit-growth=10000 -I. -I/tmp/pear/temp/igbinary -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/include -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/main -I/tmp/pear/temp/igbinary -I/opt/sp/php7.4/include/php -I/opt/sp/php7.4/include/php/main -I/opt/sp/php7.4/include/php/TSRM -I/opt/sp/php7.4/include/php/Zend -I/opt/sp/php7.4/include/php/ext -I/opt/sp/php7.4/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/igbinary/src/php7/hash_si_ptr.c  -fPIC -DPIC -o src/php7/.libs/hash_si_ptr.o
/bin/bash /tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/libtool --mode=link cc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/include -I/tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/main -I/tmp/pear/temp/igbinary -I/opt/sp/php7.4/include/php -I/opt/sp/php7.4/include/php/main -I/opt/sp/php7.4/include/php/TSRM -I/opt/sp/php7.4/include/php/Zend -I/opt/sp/php7.4/include/php/ext -I/opt/sp/php7.4/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2    -o igbinary.la -export-dynamic -avoid-version -prefer-pic -module -rpath /tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/modules  src/php7/igbinary.lo src/php7/hash_si.lo src/php7/hash_si_ptr.lo
mkdir .libs
cc -shared  src/php7/.libs/igbinary.o src/php7/.libs/hash_si.o src/php7/.libs/hash_si_ptr.o   -Wl,-soname -Wl,igbinary.so -o .libs/igbinary.so
creating igbinary.la
(cd .libs && rm -f igbinary.la && ln -s ../igbinary.la igbinary.la)
/bin/bash /tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/libtool --mode=install cp ./igbinary.la /tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/modules
cp ./.libs/igbinary.so /tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/modules/igbinary.so
cp ./.libs/igbinary.lai /tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/modules/igbinary.la
PATH="$PATH:/sbin" ldconfig -n /tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /tmp/pear/temp/pear-build-rootJZZ0ho/igbinary-3.2.5/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

running: make INSTALL_ROOT="/tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5" install
Installing shared extensions:     /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/lib/php/extensions/no-debug-non-zts-20190902/
Installing header files:          /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/include/php/
running: find "/tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5" | xargs ls -dils
100853847    0 drwxr-xr-x 3 root root      17 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5
 44050491    0 drwxr-xr-x 3 root root      16 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt
 67176634    0 drwxr-xr-x 3 root root      20 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp
100853848    0 drwxr-xr-x 4 root root      32 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4
412828701    0 drwxr-xr-x 3 root root      17 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/include
436923482    0 drwxr-xr-x 3 root root      17 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/include/php
470272037    0 drwxr-xr-x 3 root root      22 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/include/php/ext
504305847    0 drwxr-xr-x 3 root root      57 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/include/php/ext/igbinary
504305848    4 -rw-r--r-- 1 root root     261 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/include/php/ext/igbinary/igbinary.h
504305849    4 -rw-r--r-- 1 root root     788 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/include/php/ext/igbinary/php_igbinary.h
    59593    0 drwxr-xr-x 3 root root      18 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/include/php/ext/igbinary/src
 44050492    0 drwxr-xr-x 2 root root      46 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/include/php/ext/igbinary/src/php7
 44050493    4 -rw-r--r-- 1 root root    2571 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/include/php/ext/igbinary/src/php7/igbinary.h
 44050494    4 -rw-r--r-- 1 root root    2010 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/include/php/ext/igbinary/src/php7/php_igbinary.h
134528062    0 drwxr-xr-x 3 root root      17 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/lib
168297782    0 drwxr-xr-x 3 root root      24 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/lib/php
201935997    0 drwxr-xr-x 3 root root      39 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/lib/php/extensions
235116586    0 drwxr-xr-x 2 root root      25 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/lib/php/extensions/no-debug-non-zts-20190902
239355924 2928 -rwxr-xr-x 1 root root 2998272 Aug 11 11:40 /tmp/pear/temp/pear-build-rootJZZ0ho/install-igbinary-3.2.5/opt/sp/php7.4/lib/php/extensions/no-debug-non-zts-20190902/igbinary.so

Build process completed successfully
Installing '/opt/sp/php7.4/lib/php/extensions/no-debug-non-zts-20190902/igbinary.so'
Installing '/opt/sp/php7.4/include/php/ext/igbinary/src/php7/igbinary.h'
Installing '/opt/sp/php7.4/include/php/ext/igbinary/src/php7/php_igbinary.h'
Installing '/opt/sp/php7.4/include/php/ext/igbinary/igbinary.h'
Installing '/opt/sp/php7.4/include/php/ext/igbinary/php_igbinary.h'
upgrade ok: channel://pecl.php.net/igbinary-3.2.5
You should add "extension=igbinary.so" to php.ini
Segmentation fault
```

```
#dmesg
[11740731.384099] Code: 41 5d e9 63 28 ff ff 0f 1f 00 f3 0f 1e fa 8b 47 2c 85 c0 0f 85 35 41 ff ff 80 7f 28 08 0f 85 21 41 ff ff 41 54 55 53 4c 8b 67 <20> 48 89 f3 49 8b 7c 24 e8 e8 a2 28 ff ff 84 c0 75 0e 5b 5d 41 5c
[11740741.537255] traps: php-fpm[2464860] general protection fault ip:7fe6012df684 sp:7ffe54632af0 error:0 in igbinary.so[7fe6012de000+2c000]
[11740741.542279] traps: php-fpm[2465572] general protection fault ip:7fe60570975e sp:7ffe54634b88 error:0 in ld-2.31.so[7fe6056eb000+23000]
[11740741.543789] traps: php-fpm[2465573] general protection fault ip:7fe60570975e sp:7ffe54634b88 error:0 in ld-2.31.so[7fe6056eb000+23000]
[11740741.545069] traps: php-fpm[2465574] general protection fault ip:7fe60570975e sp:7ffe54634b88 error:0 in ld-2.31.so[7fe6056eb000+23000]
[11740741.546433] traps: php-fpm[2465575] general protection fault ip:7fe60570975e sp:7ffe54634b88 error:0 in ld-2.31.so[7fe6056eb000+23000]
[11740741.547726] traps: php-fpm[2465576] general protection fault ip:7fe60570975e sp:7ffe54634b88 error:0 in ld-2.31.so[7fe6056eb000+23000]
[11740741.549061] traps: php-fpm[2465577] general protection fault ip:7fe60570975e sp:7ffe54634b88 error:0 in ld-2.31.so[7fe6056eb000+23000]
[11740741.550620] traps: php-fpm[2465578] general protection fault ip:7fe60570975e sp:7ffe54634b88 error:0 in ld-2.31.so[7fe6056eb000+23000]
[11740741.551935] traps: php-fpm[2465579] general protection fault ip:7fe60570975e sp:7ffe54634b88 error:0 in ld-2.31.so[7fe6056eb000+23000]
[11740741.553216] traps: php-fpm[2465580] general protection fault ip:7fe60570975e sp:7ffe54634b88 error:0 in ld-2.31.so[7fe6056eb000+23000]
[11740750.982027] show_signal: 14 callbacks suppressed
[11740761.559592] traps: php-fpm[2464232] trap invalid opcode ip:7fe6012e84d1 sp:7ffe54635438 error:0 in igbinary.so (deleted)[7fe6012de000+2c000]
```

**Comment by TysonAndre** [comment]
This is probably a bug caused by the fact that php is running with the shared library `igbinary` installed and enabled. It doesn't have anything to do with igbinary other than 

- pecl is possibly either deleting the shared library or modifying it in place while it's still used, which causes calls to functions within the shared library such as deactivate to fail.
- `make install` is probably overwriting the file in place
- All extensions that declare shutdown functions might be affected

I suspect it may be a bug due to a change in PECL itself, the exit/unwinding process, or install scripts created by phpize, though I haven't had time to check.

A similar issue was also seen in `ast` in PHP_RSHUTDOWN_FUNCTION
`PHP_MSHUTDOWN_FUNCTION(igbinary) {`

```c
(gdb) bt
#0  0x0000000000003120 in ?? ()
#1  0x00007ffff327300f in zm_shutdown_igbinary (type=<optimized out>, module_number=<optimized out>) at /tmp/pear/temp/igbinary/src/php7/igbinary.c:450
#2  0x0000555555bf3a1f in module_destructor ()
#3  0x0000555555bed160 in module_destructor_zval ()
#4  0x0000555555bff4ba in zend_hash_graceful_reverse_destroy ()
#5  0x0000555555bee547 in zend_shutdown ()
#6  0x0000555555b82b52 in php_module_shutdown ()
#7  0x00005555557b0889 in main ()
```

```c
Installing '/path/to/lib/php/extensions/no-debug-non-zts-20190902/ast.so'
install ok: channel://pecl.php.net/ast-1.0.13
configuration option "php_ini" is not set to php.ini location
You should add "extension=ast.so" to php.ini

Program received signal SIGSEGV, Segmentation fault.
0x0000000000003250 in ?? ()
(gdb) bt
#0  0x0000000000003250 in ?? ()
#1  0x00007ffff33bf1d8 in zm_deactivate_ast (type=<optimized out>, module_number=<optimized out>) at /tmp/pear/temp/ast/ast.c:1384
#2  0x0000555555bf3cb4 in zend_deactivate_modules ()
#3  0x0000555555b81bbd in php_request_shutdown ()
#4  0x0000555555c7eba6 in do_cli ()
#5  0x00005555557b0868 in main ()
```

**Comment by TysonAndre** [comment]
https://bugs.xdebug.org/view.php?id=1729 - other maintainers have the same conclusions. You can disable igbinary in various ways when running pecl if this is really a blocker.

Though pecl has consistently installed the new versions of PECLs for me.

> I can indeed confirm this, although this only recently started to become a problem for me. It has been reported in the past (0000793), and also in other packages, such as https://github.com/pdezwart/php-amqp/issues/95 and https://github.com/grpc/grpc/issues/15210). This is not a bug in Xdebug, as it's the PECL installer that causes this by overwriting a binary that is already in use (I believe). As a workaround, you can temporarily disable xdebug.so in php.ini (by using the `;` at the start of the `zend_extension=xdebug.so` line) when running "pecl install", and then reenabling Xdebug.
> 
> cheers,
> Derick

**Comment by TysonAndre** [comment]
https://bugs.php.net/bug.php?id=79943 also says the same thing

> Yes, that's a known issue.  On Linux, it is possible to replace a
shared object file that is in use, but that likely causes issues
(the segfault in your case).  There is a detailed answer on Stack
Overflow[1].  Anyhow, this is not a php.net issue, but rather
related to the pear installer, so please report it there[2].
> [1] <https://stackoverflow.com/questions/7767325/replacing-shared-object-so-file-while-main-program-is-running#answer-7779703>
> [2] <https://pear.php.net/bugs/>

**Comment by acsfer** [comment]
Thanks for the feedback.
